# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_test', '0002_auto_20161214_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjecttest',
            name='exam_type',
            field=models.CharField(choices=[('gre', 'GRE'), ('toefl', 'TOEFL'), ('gmat', 'GMAT'), ('sat', 'SAT')], default=1, help_text='Select Exam Type: ', max_length=30),
            preserve_default=False,
        ),
    ]
