# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltest',
            name='fee',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
