# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_test', '0004_subjecttest_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjecttest',
            name='duration',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='subjecttest',
            name='per_mcq_marks',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='modeltest',
            name='exam_type',
            field=models.CharField(choices=[('gre', 'GRE'), ('tofel', 'TOFEL'), ('gmat', 'GMAT'), ('sat', 'SAT')], help_text='Select Exam Type: ', max_length=30),
        ),
    ]
