# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_test', '0007_result_myanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='myanswer',
            new_name='myanswers',
        ),
    ]
