# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 12:13
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_test', '0008_auto_20161208_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Question')),
                ('choice_a', models.CharField(blank=True, max_length=200, null=True)),
                ('choice_b', models.CharField(blank=True, max_length=200, null=True)),
                ('choice_c', models.CharField(blank=True, max_length=200, null=True)),
                ('choice_d', models.CharField(blank=True, max_length=200, null=True)),
                ('choice_e', models.CharField(blank=True, max_length=200, null=True)),
                ('choice_f', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
