# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 12:31
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_test', '0009_mcq'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='answer',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq',
            name='answer_explanation',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Answer Explanation: '),
        ),
        migrations.AddField(
            model_name='mcq',
            name='subject_test',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='model_test.SubjectTest'),
            preserve_default=False,
        ),
    ]
