# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 12:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_test', '0012_mcq_subject_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='answer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), size=None),
        ),
    ]
