# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 10:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_test', '0014_result_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='subjecttest',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='modeltest',
            name='exam_type',
            field=models.CharField(choices=[('gre', 'GRE'), ('toefl', 'TOEFL'), ('gmat', 'GMAT'), ('sat', 'SAT')], help_text='Select Exam Type: ', max_length=30),
        ),
        migrations.AlterField(
            model_name='subjecttest',
            name='subject_type',
            field=models.CharField(choices=[('quantitative', 'Quantitative'), ('verbal', 'Verbal')], help_text='Select Subject Type: ', max_length=30),
        ),
    ]
