# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 10:30
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model_test', '0015_auto_20161209_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('submission_time', models.DateTimeField(blank=True, null=True)),
                ('marks', models.IntegerField(default=0)),
                ('subject_wise_marks', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='SubjestTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('submission_time', models.DateTimeField(blank=True, null=True)),
                ('marks', models.IntegerField(default=0)),
                ('myanswers', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='result',
            name='subject_test',
        ),
        migrations.RemoveField(
            model_name='result',
            name='user',
        ),
        migrations.AddField(
            model_name='modeltest',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='subjecttest',
            name='model_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_test.ModelTest'),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.AddField(
            model_name='subjesttestresult',
            name='subject_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_test.SubjectTest'),
        ),
        migrations.AddField(
            model_name='subjesttestresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modeltestresult',
            name='model_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_test.ModelTest'),
        ),
        migrations.AddField(
            model_name='modeltestresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
