# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161201_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_img',
            field=models.ImageField(default='images/blog/my-study-notebook-blog-thumbnail.png', help_text='This image will be used in single blog page', upload_to='images/blog/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='images/blog/my-study-notebook-blog-featured.png', help_text='This image will be used in blog page or as a thumbnail in sidebar', upload_to='images/blog/'),
        ),
    ]
