# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 14:55
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('event_type', models.CharField(choices=[('skype_session', 'skype_session'), ('others', 'others')], help_text='For skype session select "skype_session".', max_length=30)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('registration_limit', models.PositiveSmallIntegerField(blank=True, default=10, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=255, null=True)),
                ('calendar_invitation_link', models.TextField(blank=True, null=True)),
                ('presenter', models.ForeignKey(help_text="Presenter should have 'usermeta' data.", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'start_time',
                'ordering': ('start_time',),
            },
        ),
        migrations.CreateModel(
            name='EventEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(max_length=100)),
                ('email_body', ckeditor.fields.RichTextField(max_length=500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skype_id', models.CharField(help_text="required for 'skype session'.", max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([('event', 'attendee')]),
        ),
    ]
