# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='calendar_invitation_link',
            new_name='google_calendar_html',
        ),
    ]
